-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 16:12:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectsDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectsDB` ;

-- -----------------------------------------------------
-- Schema projectsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectsDB` DEFAULT CHARACTER SET utf8 ;
USE `projectsDB` ;

-- -----------------------------------------------------
-- Table `projectsDB`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectsDB`.`projects` ;

CREATE TABLE IF NOT EXISTS `projectsDB`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(48) NOT NULL,
  `desc` TEXT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectsDB`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectsDB`.`keywords` ;

CREATE TABLE IF NOT EXISTS `projectsDB`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectsDB`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectsDB`.`files` ;

CREATE TABLE IF NOT EXISTS `projectsDB`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `blob` BLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectsDB`.`infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectsDB`.`infos` ;

CREATE TABLE IF NOT EXISTS `projectsDB`.`infos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mime_type` VARCHAR(30) NOT NULL,
  `size` INT NOT NULL,
  `projects_id` INT NOT NULL,
  `files_id` INT NOT NULL,
  PRIMARY KEY (`id`, `projects_id`, `files_id`),
  INDEX `fk_fileTable_Project1_idx` (`projects_id` ASC),
  INDEX `fk_file_content1_idx` (`files_id` ASC),
  CONSTRAINT `fk_fileTable_Project1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `projectsDB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_content1`
    FOREIGN KEY (`files_id`)
    REFERENCES `projectsDB`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectsDB`.`projects_has_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectsDB`.`projects_has_keywords` ;

CREATE TABLE IF NOT EXISTS `projectsDB`.`projects_has_keywords` (
  `projects_id` INT NOT NULL,
  `keywords_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `keywords_id`),
  INDEX `fk_projects_has_keywords_keywords1_idx` (`keywords_id` ASC),
  INDEX `fk_projects_has_keywords_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_projects_has_keywords_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `projectsDB`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_keywords_keywords1`
    FOREIGN KEY (`keywords_id`)
    REFERENCES `projectsDB`.`keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
